### PR TITLE
Set up project "Hello Microverse!"

### PR DESCRIPTION
**Pull request by MNisarAli**
## Hello Microverse! : Project description

- Create a new GitHub repository.
- Create a new branch according to the GitHub flow rules.
- Add a .gitignore file.
- Set up a linter for HTML and CSS and make sure that any files that are not relevant are ignored by git.
- Add a descriptive README file to the project.
- A .html file that includes a header with the text "Hello Microverse!". Use h1 tag for that.
- A .css file that includes one class with styles for your header (make it in your favorite color).
- A test.md file with the text "This file should be ignored by git".
- Make sure that the last file is actually ignored by git and is not present in your GitHub repository.

### CODE REVIEW

**Review by Santiago220991 — CHANGES_REQUESTED** [review]
Hi @MNisarAli, 
I'm Santiago your code reviewer.
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
:heavy_check_mark: No linter errors.
:heavy_check_mark: Followed GitHub flow.
:heavy_check_mark: Good README file.

## Required Changes ♻️
- Kindly make sure that your pull request has a descriptive title telling you what changes are inside. please edit it. :pray: :pray: You could try with project setup or basic configuration.

image

- Please edit your pull request summary. It should describe the introduced changes in more detail. :eyes: :eyes: 

image

_Check the comments under the review._

## Optional suggestions

[OPTIONAL] Kindly remember that the commit message should be written in the imperative tense. Please apply this in future projects. :nerd_face: :nerd_face: 

[OPTIONAL] Please remember to give your feature branches a meaningful name. It helps to know quickly what changes you introduced with that branch. Kindly apply this in future projects. :+1: :smiley: :smiley: 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MNisarAli** [comment]
Hi @Santiago220991 
Thanks for your kind review.
I'll be glad if you suggest me more edits to be a good developer.

**Review by Gopxfs — APPROVED** [review]
# 🟢 STATUS: APPROVED 🟢

## Hello @MNisarAli 👋,

Your project is complete! You followed all the requirements, feel free to merge it! 😄
Congratulations! 🎉 



## Highlights
✔️ Good PR name.
✔️ Great PR summary. Well done!
✔️ Implemented all the changes requested by the previous reviewer. Well done!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Gopxfs** [comment]
> Hi @Santiago220991 Thanks for your kind review. I'll be glad if you suggest me more edits to be a good developer.

Hey @MNisarAli. I see that you are interested in learning more, here is some useful internet content that may help you at the beginning of this journey 😄:
This [youtube channel](https://www.youtube.com/c/WebDevSimplified) is extremely useful for JavaScript beginners since it is clear and direct to the point.
This [other youtube channel](https://www.youtube.com/c/Fireship) is also very good, but for programming in general.
This [youtube channel](https://www.youtube.com/c/TheCodingTrain/about) is also great and the host is extremely wired.

Enough of youtube channels, you can also find valuable information at:
[FreeCodeCamp](https://www.freecodecamp.org/), they have amazing courses and explanations.
[The Odin Project](https://www.theodinproject.com/) is one of my favorites and I use them since these days.
> These 2 websites are also great for building projects. And this is a tip for you: building new projects is an incredible way to improve your skills, arguably the best way to do so.

For coding challenges, I recommend you my favorites websites:
[Leet code](https://leetcode.com/), I love this one because after submitting a solution, you can check your time/memory usage and also check others' solutions ordered by time/memory usage as well.
[Hackerrank](https://www.hackerrank.com/products/main/) I used this one a lot before knowing about leet code.
> Honorable mention to [Code wars](https://www.codewars.com/), one that I don't use frequently but everybody loves it.

Also, if you are interested, here is an [article](https://medium.com/@gopxfs/7-tips-for-beginners-at-software-development-f3e8c30bdacc) that I wrote aiming to help beginners. Hope some tips are useful for you! 😄.

Cheers and keep coding 😉.

**Pull request merged**
